### ISSUE TITLE
Ember Bootstrap Missing

### ISSUE THREAD

**Issue by flexyford** [iamfiscus/ember-cordova-preso-example#1]
Hello,

Thanks for the great Meetup Talk last month. It helped get me started on Ember Cordova. 

I'm trying to reproduce your example and followed the README instructions. However, running an `ember build` or `ember cdv:serve`  yields the following error:

> The Broccoli Plugin: [SimpleConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
> Error: ENOENT: no such file or directory, stat 'ember-cordova-preso-example/tmp/simple_concat-input_base_path-NaLrHEhw.tmp/0/bower_components/bootstrap/dist/css/bootstrap.css'

Looking at the `07-setup` branch, I believe `ember-bootstrap` might be missing from `master` and the `01-setup` branch.

**Comment by iamfiscus** [comment]
Hey @flexyford 

Sorry for the delay. Thanks! I'm glad it helped.

Huh well it didn't find to be in step one because that doesn't use it. However it should definitely be in Master. Still I'll add it to both. 

Great find thanks for the help!

**Comment by iamfiscus** [comment]
https://github.com/iamfiscus/ember-cordova-preso-example/commit/e6aa9c348bba614d7745096eff46b969fca4a830
